version: "3.8"

services:
  reflex:
    build: .
    container_name: reflex_app
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - .:/app
      - ./reflex.db:/app/reflex.db  # Persist SQLite database file
    command: ["reflex", "run"]
